# This file is used to configure the Travis CI tests for this repository

sudo: false


language: bash


script:
  # Formatting checks:
  # Check for files starting with a blank line
  - find . -path './.git' -prune -or -path './variants' -prune -or -type f -print0 | xargs -0 -L1 bash -c 'head -1 "$0" | grep --binary-files=without-match --regexp="^$"; if [[ "$?" == "0" ]]; then echo "Blank line found at start of $0."; false; fi'
  # Check for tabs
  - find . -path './.git' -prune -or -path './variants' -prune -or \( -not -name '*.tsv' -and -type f \) -exec grep --with-filename --line-number --binary-files=without-match --regexp=$'\t' '{}' \; -exec echo 'Tab found.' \; -exec false '{}' +
  # Check for trailing whitespace
  - find . -path './.git' -prune -or -path './variants' -prune -or \( -not -name '*.tsv' -and -type f \) -exec grep --with-filename --line-number --binary-files=without-match --regexp='[[:blank:]]$' '{}' \; -exec echo 'Trailing whitespace found.' \; -exec false '{}' +
  # Check for non-Unix line endings
  - find . -path './.git' -prune -or -path './variants' -prune -or -type f -exec grep --files-with-matches --binary-files=without-match --regexp=$'\r$' '{}' \; -exec echo 'Non-Unix EOL detected.' \; -exec false '{}' +
  # Check for blank lines at end of files
  - find . -path './.git' -prune -or -path './variants' -prune -or -type f -print0 | xargs -0 -L1 bash -c 'tail -1 "$0" | grep --binary-files=without-match --regexp="^$"; if [[ "$?" == "0" ]]; then echo "Blank line found at end of $0."; false; fi'
  # Check for files that don't end in a newline (https://stackoverflow.com/a/25686825)
  - find . -path './.git' -prune -or -path './variants' -prune -or -type f -print0 | xargs -0 -L1 bash -c 'if test "$(grep --files-with-matches --binary-files=without-match --max-count=1 --regexp='.*' "$0")" && test "$(tail --bytes=1 "$0")"; then echo "No new line at end of $0."; false; fi'

  # Check for typos
  - git clone https://github.com/ss18/grep-typos.git "${HOME}/scripts/grep-typos"
  - find . -path "./.git" -prune -or -path './variants' -prune -or -type f -print0 | xargs --null --max-args=1 bash "${HOME}/scripts/grep-typos/grep_typos.sh" "$0"
  - rm "${HOME}/scripts/grep-typos" --recursive --force


notifications:
  email:
    on_success: always
    on_failure: always
  webhooks:
    urls:
      - https://www.travisbuddy.com/
    on_success: never
    on_failure: always
